# Generated by Django 6.0.1 on 2026-02-06 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="update_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
